// Generated by CoffeeScript 1.6.3
var Index, fs, jade, path;

(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

fs = require('fs');

path = require('path');

jade = require('jade');

module.exports = new (Index = (function() {
  function Index() {}

  Index.prototype.polvo = true;

  Index.prototype.type = 'js';

  Index.prototype.name = 'jade';

  Index.prototype.ext = /\.jade$/m;

  Index.prototype.exts = ['.jade'];

  Index.prototype.compile = function(filepath, source, debug, done) {
    var compiled, err;
    try {
      compiled = jade.compile(source, {
        filename: filepath,
        client: true,
        compileDebug: debug
      });
    } catch (_error) {
      err = _error;
      throw err;
    }
    return done('module.exports = ' + compiled, null);
  };

  Index.prototype.fetch_helpers = function() {
    var filepath;
    filepath = path.join(__dirname, 'node_modules', 'jade', 'runtime.js');
    return fs.readFileSync(filepath, 'utf-8');
  };

  return Index;

})());
