// Generated by CoffeeScript 1.6.3
var Index, clone, fs, jade, path;

(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

fs = require('fs');

path = require('path');

jade = require('jade');

clone = require('regexp-clone');

module.exports = new (Index = (function() {
  var has_deps, match_all_deps;

  function Index() {}

  Index.prototype.type = 'template';

  Index.prototype.name = 'jade';

  Index.prototype.output = 'js';

  Index.prototype.ext = /\.jade$/m;

  Index.prototype.exts = ['.jade'];

  Index.prototype.partials = true;

  has_deps = /^\s*(?:(?!\/\/).?)(?:include|extends)\s/m;

  match_all_deps = /^\s*(?:(?!\/\/).?)(?:include|extends)\s+(\S+)/mg;

  Index.prototype.is_partial = function(filepath) {
    return /^_/m.test(path.basename(filepath));
  };

  Index.prototype.compile = function(filepath, source, debug, error, done) {
    var compiled, err;
    try {
      compiled = jade.compile(source, {
        filename: filepath,
        client: true,
        compileDebug: debug
      });
    } catch (_error) {
      err = _error;
      error(err);
      return done('', null);
    }
    return done('module.exports = ' + compiled, null);
  };

  Index.prototype.resolve_dependents = function(filepath, files) {
    var all, dependents, dirpath, each, has, include, match, name, sub, _i, _len, _ref;
    dependents = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      each = files[_i];
      _ref = [clone(has_deps), clone(match_all_deps)], has = _ref[0], all = _ref[1];
      if (!has.test(each.raw)) {
        continue;
      }
      dirpath = path.dirname(each.filepath);
      name = path.basename(each.filepath);
      while ((match = all.exec(each.raw)) != null) {
        include = match[1];
        include = include.replace(this.ext, '') + '.jade';
        include = path.join(dirpath, include);
        if (include === filepath) {
          if (!this.is_partial(name)) {
            dependents.push(each);
          } else {
            sub = this.resolve_dependents(each.filepath, files);
            dependents = dependents.concat(sub);
          }
        }
      }
    }
    return dependents;
  };

  Index.prototype.fetch_helpers = function() {
    var filepath;
    filepath = path.join(__dirname, '..', 'node_modules', 'jade');
    filepath = path.join(filepath, 'runtime.js');
    return fs.readFileSync(filepath, 'utf-8');
  };

  return Index;

})());

/*
//@ sourceMappingURL=index.map
*/
